[build]
  base = "adhd-voice-assistant"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_OPENAI_API_KEY = ""
  NEXT_PUBLIC_AIRTABLE_API_KEY = ""
  NEXT_PUBLIC_AIRTABLE_BASE_ID = ""
  NEXT_PUBLIC_AIRTABLE_TABLE_NAME = "tasks"

[[plugins]]
  package = "@netlify/plugin-nextjs" 